#!/bin/bash

export LD_LIBRARY_PATH=`pwd`/../build/lib:`pwd`/../x264/lib

case "$1" in
	hello)
	./hello ${@:2}
	;;
	remuxer)
	./remuxer ${@:2}
	;;
	decoder)
	./decoder ${@:2}
	;;
	transcode)
	./transcode ${@:2}
	;;
	clear)
	rm *.flv *.mp4 *.pgm -f
	;;
    *)
	echo "Usage: run.sh {start|clear} "
	exit 1
esac

exit $?